---
title: "DS_project1"
author: "Jane"
date: "3/22/2022"
output: html_document
---

```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r}
## Importing packages
library(tidyverse) 
library(MASS)
library(car)
library(e1071)
library(caret)
library(cowplot)
library(caTools)
library(pROC)
library(ggcorrplot)
```
## project1
##  the behavior of telecom customers who are more likely to leave the platform. I intend to find out the most striking behavior of customers through EDA

```{r}
telco = data.frame(read.csv("Telco_customer_churn.csv", header = TRUE))
head(telco, n=10)
# 33 variables.
```



```{r}
colnames(telco)
```


```{r}

is.null(telco)
```

```{r}
summary(telco)
```

```{r}
library(Hmisc)
describe(telco)

```











